services:
  minio:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z
    command: server /data --console-address :9001
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:9000/minio/health/live
    networks:
      big-data-net:

  spark:
    image: apache/spark:3.5.6-java17-python3
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - 8080:8080
      - 7077:7077
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080
    volumes:
      - ./airflow/jobs:/opt/airflow/jobs
    networks:
      big-data-net:

  spark-worker:
    image: apache/spark:3.5.6-java17-python3
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark:7077
    deploy:
      replicas: 1
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8081
    volumes:
      - ./airflow/jobs:/opt/airflow/jobs
    networks:
      big-data-net:
  
  airflow:
    build: .
    image: airflow-image
    command: standalone
    environment:
      - AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS=True
      - HADOOP_CONF_DIR=/opt/hadoop_conf
    ports:
      - 8090:8080
    volumes:
      - airflow_data:/opt/airflow/data
      - airflow_cache:/opt/airflow/cache
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/jobs:/opt/airflow/jobs
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080
    networks:
      big-data-net:

volumes:
  minio_data:
  airflow_data:
  airflow_cache:

networks:
  big-data-net:
    driver: bridge
