services:
  minio:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z
    command: server /data --console-address :9001
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:9000/minio/health/live
    networks:
      big-data-net:

  spark:
    image: apache/spark:3.5.6-java17-python3
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - 8080:8080
      - 7077:7077
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080
    volumes:
      - ./airflow/jobs:/opt/airflow/jobs
    networks:
      big-data-net:

  spark-worker:
    image: apache/spark:3.5.6-java17-python3
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark:7077
    deploy:
      replicas: 1
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8081
    volumes:
      - ./airflow/jobs:/opt/airflow/jobs
    networks:
      big-data-net:
  
  airflow:
    build: .
    image: airflow-image
    command: standalone
    environment:
      - AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS=True
      - HADOOP_CONF_DIR=/opt/hadoop_conf
    ports:
      - 8090:8080
    volumes:
      - airflow_data:/opt/airflow/data
      - airflow_cache:/opt/airflow/cache
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/jobs:/opt/airflow/jobs
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080
    networks:
      big-data-net:

  metastore-db:
    image: postgres
    container_name: metastore-db
    hostname: metastore-db
    environment:
      - POSTGRES_DB=metastore_db
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
    volumes:
      - postgres_metastore_data:/var/lib/postgresql/data
    networks:
      big-data-net:

  hive-metastore:
    hostname: hive-metastore
    image: 'starburstdata/hive:3.1.2-e.18'
    ports:
      - '9083:9083' # Metastore Thrift
    environment:
      HIVE_METASTORE_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_JDBC_URL: jdbc:postgresql://metastore-db:5432/metastore_db
      HIVE_METASTORE_USER: hive
      HIVE_METASTORE_PASSWORD: hive
      HIVE_METASTORE_WAREHOUSE_DIR: s3a://hudi-bucket-test/hive
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_PATH_STYLE_ACCESS: "true"
      REGION: ""
      GOOGLE_CLOUD_KEY_FILE_PATH: ""
      AZURE_ADL_CLIENT_ID: ""
      AZURE_ADL_CREDENTIAL: ""
      AZURE_ADL_REFRESH_URL: ""
      AZURE_ABFS_STORAGE_ACCOUNT: ""
      AZURE_ABFS_ACCESS_KEY: ""
      AZURE_WASB_STORAGE_ACCOUNT: ""
      AZURE_ABFS_OAUTH: ""
      AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
      AZURE_ABFS_OAUTH_CLIENT_ID: ""
      AZURE_ABFS_OAUTH_SECRET: ""
      AZURE_ABFS_OAUTH_ENDPOINT: ""
      AZURE_WASB_ACCESS_KEY: ""
      HIVE_METASTORE_USERS_IN_ADMIN_ROLE: "admin"
    depends_on:
      - metastore-db
    networks:
      big-data-net:

volumes:
  minio_data:
  airflow_data:
  airflow_cache:

networks:
  big-data-net:
    driver: bridge
